spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database?currentSchema=badminton
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # hoặc 'validate' khi deploy production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081
#  servlet:
#    context-path: /user

logging :
  level :
    org.springframework.security : DEBUG

jwt :
  signer_key : "H/iI+s4RM9/p2zSeTtC5u9HM9QzH1IHLZYV/yOVTwf9hCvfaxKwl19hRm0Hw3344"
